version: '2.1'
orbs:
  node: circleci/node@4.2
jobs:
  test:
    executor:
      name: node/default
      tag: '14.16.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
workflows:
  test_my_app:
    jobs:
      - test